CREATE OR REPLACE 
PACKAGE PKG_USUARIO AS 

  PROCEDURE SP_VALIDAR_ACCESO(
    P_CURSOR OUT SYS_REFCURSOR,
    p_USUARIO IN USUARIO.USUARIO%TYPE,
    p_CLAVE IN USUARIO.CLAVE%TYPE
  );
  
    PROCEDURE SP_LISTAR(
    P_CURSOR OUT SYS_REFCURSOR,
    P_USUARIO IN USUARIO.USUARIO%TYPE,
    P_NOMBRE  IN USUARIO.NOMBRE%TYPE
  );
  
    PROCEDURE SP_INSERTAR(
    P_ID_USUARIO    OUT USUARIO.ID_USUARIO%TYPE,
    P_USUARIO       IN  USUARIO.USUARIO%TYPE,
    P_CLAVE         IN  USUARIO.CLAVE%TYPE,
    P_NOMBRE        IN  USUARIO.NOMBRE%TYPE
  );

END PKG_USUARIO;
