CREATE TABLE PAIS(
    ID_PAIS NUMERIC(10) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(120) NOT NULL UNIQUE,
    SIGLA CHAR(3) NOT NULL, 
    ESTADO CHAR(1) DEFAULT '1' NOT NULL
);

CREATE SEQUENCE SEQ_PAIS;

INSERT INTO PAIS (ID_PAIS, NOMBRE, SIGLA)
VALUES(SEQ_PAIS.NEXTVAL, 'PERU','PER');
INSERT INTO PAIS (ID_PAIS, NOMBRE, SIGLA)
VALUES(SEQ_PAIS.NEXTVAL, 'MEXICO','MXN');
INSERT INTO PAIS (ID_PAIS, NOMBRE, SIGLA)
VALUES(SEQ_PAIS.NEXTVAL, 'ECUADOR','ECU');


COMMIT;

SELECT ID_PAIS, NOMBRE, SIGLA FROM PAIS;

CREATE TABLE CLIENTE(
    CLIENTE_ID NUMERIC(6) NOT NULL PRIMARY KEY,
    RAZON_SOCIAL VARCHAR2(260) NOT NULL,
    NRO_DOCUMENTO VARCHAR2(60) NULL,
    CORREO VARCHAR2(60) NULL,
    DIRECCION VARCHAR2(220) NULL,
    
    ID_PAIS NUMERIC(3) NOT NULL REFERENCES PAIS(ID_PAIS),
    
    ESTADO CHAR(1) DEFAULT '1' NOT NULL,
    
    AUD_TIPO CHAR(1) NOT NULL,
    AUD_IDUSUARIO NUMERIC(4) NOT NULL,
    AUD_SESION VARCHAR2(60) NULL,
    AUD_IP VARCHAR2(20) NULL,
    AUD_FECHA DATE NULL 
);


CREATE SEQUENCE SEQ_CLIENTE;

INSERT INTO CLIENTE(CLIENTE_ID,RAZON_SOCIAL,NRO_DOCUMENTO,CORREO,DIRECCION,ID_PAIS,AUD_TIPO,AUD_IDUSUARIO)
VALUES(SEQ_CLIENTE.NEXTVAL, 'TELEFONICA DEL PERU S.A.A', '20100017491','contacto@movistar.com.pe',
'Jirón Domingo Martinez Luján 1130 - Surquillo - Lima',1,'I',1);



COMMIT;

SELECT CLIENTE_ID,RAZON_SOCIAL,NRO_DOCUMENTO,CORREO,DIRECCION,ID_PAIS FROM CLIENTE;